const nextPlugin = require('@next/eslint-plugin-next')
const tseslint = require('typescript-eslint')
const reactHooksPlugin = require('eslint-plugin-react-hooks')
const importPlugin = require('eslint-plugin-import')
const storybookPlugin = require('eslint-plugin-storybook')

const eslintConfig = [
  // Global ignores - these apply to all configurations
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      '.vercel/**',
      '.git/**',
      'dist/**',
      'build/**',
      'coverage/**',
      'public/**',
      '*.min.js',
      'next.config.ts', // Next.js config can have special patterns
      'next-env.d.ts', // Generated by Next.js
      'tailwind.config.ts', // Tailwind config can have special patterns
      'vitest.config.ts', // Vitest config can have special patterns
      'vitest.setup.ts', // Vitest setup can have special patterns
      'postcss.config.js', // PostCSS config usually minimal
      'prettier.config.js', // Prettier config usually minimal
      'sanity.config.ts', // Sanity config can have special patterns
      'sanity.cli.ts', // Sanity CLI config
      '__tests__/**/*.test.{js,ts,tsx}',
      '__tests__/**/testdata/**',
      '__tests__/**/mocks/**',
      'storybook-static/**', // Built Storybook output
    ],
  },

  // TypeScript configuration
  ...tseslint.configs.recommended,

  // Storybook configuration
  ...storybookPlugin.configs['flat/recommended'],

  // Main configuration for TypeScript and JavaScript files
  {
    plugins: {
      '@next/next': nextPlugin,
      'react-hooks': reactHooksPlugin,
      import: importPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      ...reactHooksPlugin.configs.recommended.rules,
    },
  },

  {
    rules: {
      '@next/next/no-img-element': 'off',
      'import/no-anonymous-default-export': 'off',
      // Disable strict React Hooks rules from Next.js 16 for now
      // These are performance optimizations, not bugs - can be addressed incrementally
      'react-hooks/set-state-in-effect': 'warn', // Warn instead of error for setState in effects
      'react-hooks/static-components': 'warn', // Warn instead of error for inline components
      'react-hooks/purity': 'warn', // Warn instead of error for impure functions
      'react-hooks/error-boundaries': 'off', // Server Components don't need try/catch for JSX
    },
  },

  // Special rules for ESLint config file
  {
    files: ['eslint.config.js'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off', // CommonJS required for compatibility
    },
  },

  // Special rules for migration files
  {
    files: ['migrations/**/*.{js,ts}'],
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_|context' },
      ], // Allow unused context parameter
    },
  },

  // Special rules for Sanity schema files
  {
    files: ['sanity/schemaTypes/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off', // Sanity schemas often need any types
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_|error' },
      ],
    },
  },
]

module.exports = eslintConfig
