const nextPlugin = require('@next/eslint-plugin-next')
const tseslint = require('typescript-eslint')
const reactHooksPlugin = require('eslint-plugin-react-hooks')
const importPlugin = require('eslint-plugin-import')
const storybookPlugin = require('eslint-plugin-storybook')
const noUnscopedGroq = require('./eslint-rules/no-unscoped-groq')
const noBareAmountParse = require('./eslint-rules/no-bare-amount-parse')

const eslintConfig = [
  // Global ignores - these apply to all configurations
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      // Agent git worktrees. Each is a full checkout WITH ITS OWN tsconfig.json,
      // so typescript-eslint sees several candidate roots and fails EVERY file
      // in the repo with "No tsconfigRootDir was set, and multiple candidate
      // TSConfigRootDirs are present" — turning a normal lint run into
      // thousands of parse errors. That is not a hypothetical: it made
      // `pnpm lint` unusable for a whole working session, which is part of why
      // 254 warnings went unread. Nothing here is source we ship.
      '.claude/**',
      '.vercel/**',
      '.git/**',
      'dist/**',
      'build/**',
      'coverage/**',
      'public/**',
      '*.min.js',
      // Playwright e2e scaffold: imports @playwright/test, which is installed
      // on demand (see e2e/README.md), so keep it out of the standard lint pass.
      'e2e/**',
      'playwright.config.ts',
      'test-results/**',
      'playwright-report/**',
      'next.config.ts', // Next.js config can have special patterns
      'next-env.d.ts', // Generated by Next.js
      'tailwind.config.ts', // Tailwind config can have special patterns
      'vitest.config.ts', // Vitest config can have special patterns
      'vitest.setup.ts', // Vitest setup can have special patterns
      'postcss.config.js', // PostCSS config usually minimal
      'prettier.config.js', // Prettier config usually minimal
      'sanity.config.ts', // Sanity config can have special patterns
      'sanity.cli.ts', // Sanity CLI config
      '__tests__/**/*.test.{js,ts,tsx}',
      '__tests__/**/testdata/**',
      '__tests__/**/mocks/**',
      'storybook-static/**', // Built Storybook output
      'cli/**',
    ],
  },

  // TypeScript configuration
  ...tseslint.configs.recommended,

  // Storybook configuration
  ...storybookPlugin.configs['flat/recommended'],

  // Pin the TypeScript project root.
  //
  // typescript-eslint discovers candidate roots by looking for tsconfig.json,
  // and that scan happens BEFORE `ignores` is applied — so a single git
  // worktree under `.claude/worktrees/` (each is a full checkout with its own
  // tsconfig) makes it abort with "No tsconfigRootDir was set, and multiple
  // candidate TSConfigRootDirs are present" on EVERY file. That turned a normal
  // lint run into ~1700 parse errors and made `pnpm lint` unusable for a whole
  // working session, which is a large part of why 254 warnings went unread.
  // Naming the root removes the ambiguity permanently.
  {
    languageOptions: {
      parserOptions: {
        tsconfigRootDir: __dirname,
      },
    },
  },

  // Main configuration for TypeScript and JavaScript files
  {
    plugins: {
      '@next/next': nextPlugin,
      'react-hooks': reactHooksPlugin,
      import: importPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      ...reactHooksPlugin.configs.recommended.rules,
    },
  },

  {
    rules: {
      '@next/next/no-img-element': 'off',
      'import/no-anonymous-default-export': 'off',
      // Disable strict React Hooks rules from Next.js 16 for now
      // These are performance optimizations, not bugs - can be addressed incrementally
      'react-hooks/set-state-in-effect': 'warn', // Warn instead of error for setState in effects
      'react-hooks/static-components': 'warn', // Warn instead of error for inline components
      'react-hooks/purity': 'warn', // Warn instead of error for impure functions
      'react-hooks/error-boundaries': 'off', // Server Components don't need try/catch for JSX
    },
  },

  // Tenant-scoped query invariant (CaaS #616). WARN, not error: the repo has
  // ~170 pre-existing unscoped queries, so an error would block CI. This makes
  // NEW unscoped `*[_type == ...` queries visible in review and keeps the
  // outstanding count trackable. The rule self-exempts the scoped builder
  // module, tests, scripts, and migrations. See docs/TENANT_SCOPING.md.
  //
  // The glob covers every executable extension, not just `{ts,tsx}`, even
  // though the repo is all-TypeScript: a narrower glob meant a `.js` file under
  // `src/` was never linted at all, so the identical unscoped query that fails
  // the ratchet as `.ts` shipped silently as `.js`. The same holds for `.mjs`
  // and `.cjs` (webpack resolves them) and `.mts`/`.cts` (tsc compiles them).
  // Nothing mechanical stops someone adding one.
  {
    files: ['src/**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}'],
    plugins: {
      tenancy: { rules: { 'no-unscoped-groq': noUnscopedGroq } },
    },
    rules: {
      'tenancy/no-unscoped-groq': 'warn',
    },
  },

  // One parse for every ticketing-provider money string (#898). ERROR, not a
  // warning behind a ratchet like the rule above: the sweep took the count to
  // zero, so there is nothing to grandfather, and a ratchet pinned at 0 only
  // fails on a per-file INCREASE and needs a second CI step to be read at all.
  // A genuine exception is annotated (`// amount-parse-ok: <reason>` /
  // `// not-an-amount: <why>`) and shows up in the diff. The rule self-exempts
  // src/lib/tickets/amount.ts — the module that owns the NaN policy — plus
  // tests, stories, scripts and migrations. Glob includes `js`/`jsx` for the
  // same reason as the rule above: an unlinted extension is a bypass.
  {
    files: ['src/**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}'],
    plugins: {
      money: { rules: { 'no-bare-amount-parse': noBareAmountParse } },
    },
    rules: {
      'money/no-bare-amount-parse': 'error',
    },
  },

  // Special rules for ESLint config file + local ESLint rules (CommonJS).
  {
    files: ['eslint.config.js', 'eslint-rules/**/*.js'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off', // CommonJS required for compatibility
    },
  },

  // Special rules for migration files
  {
    files: ['migrations/**/*.{js,ts}'],
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_|context' },
      ], // Allow unused context parameter
    },
  },

  // `sanity migration list` loads every migration through the CLI's own
  // loader, which cannot parse `.tsx`. A `@/lib/<dir>` barrel re-exports
  // whatever else lives in that directory, so one barrel import breaks
  // migration discovery for all migrations. Import the exact module instead.
  // Test files are exempt: they run under vitest, never the Sanity loader.
  {
    files: ['migrations/**/*.{js,ts}'],
    ignores: ['migrations/**/*.test.{js,ts}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              // Single-segment `@/lib/x` only — deep paths like
              // `@/lib/speaker/slug` are exactly what we want instead.
              regex: '^@/lib/[^/]+$',
              message:
                'Import the specific module (e.g. @/lib/proposal/utils/validation), not a barrel — barrels break `sanity migration list`.',
            },
          ],
        },
      ],
    },
  },

  // Special rules for Sanity schema files
  {
    files: ['sanity/schemaTypes/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off', // Sanity schemas often need any types
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_|error' },
      ],
    },
  },
]

module.exports = eslintConfig
