export { SIGNATURE_MARKER, DATE_MARKER } from './constants'
export { findMarkerInPdf, parseTextPosition } from './marker-detection'
export type { MarkerPosition } from './marker-detection'
export { embedSignatureInPdf } from './signature-embed'
export { addAttestationPage } from './attestation-page'
export type { SigningAttestation } from './attestation-page'
