import { chromium } from 'playwright'
const b = await chromium.launch({ channel: 'chrome', headless: false })
const p = await b.newPage()
p.on('console', (m) => /cancel|result/.test(m.text()) && console.log(m.text().slice(0, 300)))
await p.goto('http://127.0.0.1:4817/?mode=auto&seconds=60&label=chrome-click-cancel')
await p.click('#start')
await p.waitForFunction(() => parseInt(document.getElementById('pct').textContent) >= 20, null, { timeout: 60000 })
const pct = await p.textContent('#pct')
const t = Date.now()
await p.mouse.click(...(await p.locator('#cancel').boundingBox().then((bb) => [bb.x + bb.width / 2, bb.y + bb.height / 2])))
console.log('clicked at', pct, 'click returned after', Date.now() - t, 'ms')
await p.waitForFunction(() => document.title.startsWith('DONE'), null, { timeout: 60000 })
await p.screenshot({ path: 'scratch/video-proof/out/chrome-click-cancel.png' })
await b.close()
