/**
 * Ref materialisation for the visual-diff harness.
 *
 * Capturing `main` and your working tree in one sitting means having both on
 * disk at once. Rather than stashing and checking out (which loses uncommitted
 * work if anything goes wrong), each ref is checked out into a throwaway
 * detached `git worktree` under the output dir, with `node_modules` symlinked
 * from the primary checkout so no second install is needed.
 */
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import fs from 'node:fs/promises'
import path from 'node:path'

const exec = promisify(execFile)

async function git(cwd, args) {
  const { stdout } = await exec('git', args, {
    cwd,
    maxBuffer: 32 * 1024 * 1024,
  })
  return stdout.trim()
}

export async function repoRoot(cwd = process.cwd()) {
  return git(cwd, ['rev-parse', '--show-toplevel'])
}

/** Describe a ref (or the working tree, when `ref` is null) for the manifest. */
export async function describeTree(root, ref) {
  if (!ref) {
    const sha = await git(root, ['rev-parse', 'HEAD'])
    const dirty = (await git(root, ['status', '--porcelain'])).length > 0
    return { ref: 'WORKTREE', sha, dirty, subject: await subjectOf(root, sha) }
  }
  const sha = await git(root, ['rev-parse', '--verify', `${ref}^{commit}`])
  return { ref, sha, dirty: false, subject: await subjectOf(root, sha) }
}

async function subjectOf(root, sha) {
  return git(root, ['log', '-1', '--format=%s', sha])
}

/**
 * Check `ref` out into `dir` and make it runnable.
 *
 * @param {{root: string, ref: string|null, dir: string,
 *   log?: (msg: string) => void}} options
 * @returns {Promise<{dir: string, cleanup: () => Promise<void>}>}
 *   With `ref === null` the primary checkout is used as-is (so an uncommitted
 *   working tree is exactly what gets captured) and cleanup is a no-op.
 */
export async function materializeRef({ root, ref, dir, log = () => {} }) {
  if (!ref) return { dir: root, cleanup: async () => {} }

  await removeWorktree(root, dir)
  await fs.mkdir(path.dirname(dir), { recursive: true })
  log(`checking ${ref} out into ${path.relative(root, dir)} …`)
  await git(root, ['worktree', 'add', '--detach', '--force', dir, ref])

  // Vite resolves through symlinks to the real path, so the worktree's source
  // files still compile against the primary checkout's installed packages.
  const link = path.join(dir, 'node_modules')
  if (!(await exists(link))) {
    await fs.symlink(path.join(root, 'node_modules'), link, 'dir')
    log('symlinked node_modules from the primary checkout')
  }

  // `public/mockServiceWorker.js` is gitignored (generated by `msw init`), so a
  // fresh checkout does not have it — and without it EVERY story renders MSW's
  // "failed to register a Service Worker" error screen instead of a component.
  await copyIgnoredArtifact(root, dir, 'public/mockServiceWorker.js', log)

  return {
    dir,
    // Failing to tidy a temporary directory must never fail a capture that
    // already succeeded — the run's output is on disk and is what matters.
    // `git worktree prune` (or the next run) will pick up whatever is left.
    cleanup: async () => {
      try {
        await fs.rm(link, { force: true })
        await removeWorktree(root, dir)
      } catch (error) {
        log(`WARNING: could not remove ${dir}: ${error?.message ?? error}`)
      }
    },
  }
}

async function copyIgnoredArtifact(root, dir, rel, log) {
  const from = path.join(root, rel)
  if (!(await exists(from))) {
    log(
      `WARNING: ${rel} is missing from the primary checkout — run \`pnpm exec msw init public\``,
    )
    return
  }
  await fs.mkdir(path.dirname(path.join(dir, rel)), { recursive: true })
  await fs.copyFile(from, path.join(dir, rel))
}

async function removeWorktree(root, dir) {
  if (!(await exists(dir))) return
  await git(root, ['worktree', 'remove', '--force', dir]).catch(async () => {
    await fs.rm(dir, { recursive: true, force: true })
    await git(root, ['worktree', 'prune']).catch(() => {})
  })
}

async function exists(p) {
  try {
    await fs.lstat(p)
    return true
  } catch {
    return false
  }
}
