import type { ConferenceBudgetDocument } from './types'

/**
 * Seed template for a new conference budget. The STRUCTURE (ticket-mix
 * mechanics, cost categories, optional-cost flags, scenario shapes) mirrors
 * the CloudNativeBergen/budget generator; the FIGURES are deliberately
 * generic, plausibly-rounded placeholders — seeds are generic by design in
 * a multi-tenant platform, and every number is a starting point the
 * organizers are expected to replace with their own quotes. Real
 * per-conference figures belong in the budget document (data), never here.
 *
 * `_key`s are stable slugs so the seeded scenarios can cross-reference
 * rows; newly added rows get generated keys via `ensureUniqueArrayKeys`.
 */

type SeedDocument = Omit<ConferenceBudgetDocument, '_id' | 'conference'>

function scenario(
  key: string,
  name: string,
  description: string,
  tickets: Record<string, number>,
  tiers: Record<string, number>,
  addons: Record<string, number>,
  cutCosts: string[] = [],
): NonNullable<SeedDocument['scenarios']>[number] {
  return {
    _key: key,
    name,
    description,
    ticketCounts: Object.entries(tickets).map(([ticketType, quantity]) => ({
      _key: `ticket-${ticketType}`,
      ticketType,
      quantity,
    })),
    tierCounts: Object.entries(tiers).map(([tier, count]) => ({
      _key: `tier-${tier}`,
      tier,
      count,
    })),
    addonCounts: Object.entries(addons).map(([addon, count]) => ({
      _key: `addon-${addon}`,
      addon,
      count,
    })),
    cutCosts,
  }
}

export function defaultBudgetSeed(): SeedDocument {
  return {
    _type: 'conferenceBudget',
    vatRate: 0.25,
    ticketingFeeRate: 0.045,
    dinnerParticipation: { floor: 0.4, base: 0.9, decay: 1000 },
    ticketTypes: [
      {
        _key: 'conf-early-bird',
        name: 'Conference - Early Bird',
        priceInclVat: 2500,
        attendsConference: true,
        attendsWorkshop: false,
        workshopCrew: false,
      },
      {
        _key: 'conf-standard',
        name: 'Conference - Standard',
        priceInclVat: 3125,
        attendsConference: true,
        attendsWorkshop: false,
        workshopCrew: false,
      },
      {
        _key: 'conf-late-bird',
        name: 'Conference - Late Bird',
        priceInclVat: 3750,
        attendsConference: true,
        attendsWorkshop: false,
        workshopCrew: false,
      },
      {
        _key: 'ws-early-bird',
        name: 'Conference + Workshop - Early Bird',
        priceInclVat: 5500,
        attendsConference: true,
        attendsWorkshop: true,
        workshopCrew: false,
      },
      {
        _key: 'ws-standard',
        name: 'Conference + Workshop - Standard',
        priceInclVat: 5500,
        attendsConference: true,
        attendsWorkshop: true,
        workshopCrew: false,
      },
      {
        _key: 'ws-late-bird',
        name: 'Conference + Workshop - Late Bird',
        priceInclVat: 6500,
        attendsConference: true,
        attendsWorkshop: true,
        workshopCrew: false,
      },
      {
        _key: 'student',
        name: 'Student',
        priceInclVat: 1337,
        attendsConference: true,
        attendsWorkshop: false,
        workshopCrew: false,
      },
      {
        _key: 'sponsor-included',
        name: 'Sponsor Included',
        priceInclVat: 0,
        attendsConference: true,
        attendsWorkshop: false,
        workshopCrew: false,
        sponsorIncluded: true,
      },
      {
        _key: 'sponsor-discount',
        name: 'Sponsor Discount (20%)',
        priceInclVat: 2500,
        attendsConference: true,
        attendsWorkshop: false,
        workshopCrew: false,
      },
      {
        _key: 'sponsor-ws-upgrade',
        name: 'Sponsor Workshop Upgrade',
        priceInclVat: 1500,
        attendsConference: false,
        attendsWorkshop: true,
        workshopCrew: false,
      },
      {
        _key: 'speaker',
        name: 'Speaker',
        priceInclVat: 0,
        attendsConference: true,
        attendsWorkshop: false,
        workshopCrew: true,
      },
      {
        _key: 'organizer',
        name: 'Organizer',
        priceInclVat: 0,
        attendsConference: true,
        attendsWorkshop: false,
        workshopCrew: true,
      },
      {
        _key: 'volunteer',
        name: 'Volunteer',
        priceInclVat: 0,
        attendsConference: true,
        attendsWorkshop: false,
        workshopCrew: true,
      },
    ],
    sponsorTierAssumptions: [
      {
        _key: 'community-partner',
        name: 'Community Partner',
        priceExVat: 25000,
        includedTickets: 2,
      },
    ],
    sponsorAddonAssumptions: [
      { _key: 'streaming', name: 'Streaming Sponsor', priceExVat: 20000 },
      { _key: 'speakers-dinner', name: 'Speakers Dinner', priceExVat: 30000 },
      { _key: 'lanyard', name: 'Lanyard Sponsor', priceExVat: 25000 },
      { _key: 'barista', name: 'Barista Bar', priceExVat: 25000 },
      { _key: 'track', name: 'Track Sponsor', priceExVat: 20000 },
      { _key: 'afterparty', name: 'The Afterparty', priceExVat: 20000 },
    ],
    variableCosts: [
      {
        _key: 'd2-lunch',
        name: 'Conference-day lunch',
        category: 'catering',
        amountPerPerson: 300,
        basis: 'conference',
      },
      {
        _key: 'd2-coffee',
        name: 'Conference-day coffee & snacks',
        category: 'catering',
        amountPerPerson: 350,
        basis: 'conference',
      },
      {
        _key: 'dinner',
        name: 'Dinner (buffet)',
        category: 'catering',
        amountPerPerson: 600,
        basis: 'dinner',
      },
      {
        _key: 'drinks',
        name: 'Dinner drinks',
        category: 'catering',
        amountPerPerson: 200,
        basis: 'dinner',
      },
      {
        _key: 'd1-lunch',
        name: 'Workshop-day lunch',
        category: 'catering',
        amountPerPerson: 300,
        basis: 'workshop',
      },
      {
        _key: 'd1-coffee',
        name: 'Workshop-day coffee & snacks',
        category: 'catering',
        amountPerPerson: 200,
        basis: 'workshop',
      },
      {
        _key: 'badge',
        name: 'Badge & lanyard',
        category: 'other',
        amountPerPerson: 50,
        basis: 'conference',
      },
      {
        _key: 'swag',
        name: 'Swag & stickers',
        category: 'other',
        amountPerPerson: 50,
        basis: 'conference',
      },
    ],
    fixedCosts: [
      {
        _key: 'venue-conference',
        name: 'Venue - conference day',
        category: 'venue',
        amount: 100000,
        optional: false,
      },
      {
        _key: 'venue-workshop',
        name: 'Venue - workshop day',
        category: 'venue',
        amount: 40000,
        optional: false,
      },
      {
        _key: 'sound-tech',
        name: 'Sound technicians',
        category: 'venue',
        amount: 25000,
        optional: false,
      },
      {
        _key: 'streaming-av',
        name: 'Streaming / AV production',
        category: 'production',
        amount: 100000,
        optional: true,
      },
      {
        _key: 'photography',
        name: 'Photography',
        category: 'production',
        amount: 50000,
        optional: true,
      },
      {
        _key: 'print',
        name: 'Print materials',
        category: 'marketing',
        amount: 40000,
        optional: false,
      },
      {
        _key: 'barista-bar',
        name: 'Barista bar',
        category: 'catering',
        amount: 15000,
        optional: true,
      },
      {
        _key: 'speaker-travel',
        name: 'Speaker travel support',
        category: 'speakers',
        amount: 25000,
        optional: false,
      },
      {
        _key: 'speaker-dinner',
        name: 'Speaker & organizer dinner',
        category: 'speakers',
        amount: 120000,
        optional: false,
      },
      {
        _key: 'other-travel',
        name: 'Other travel',
        category: 'speakers',
        amount: 10000,
        optional: false,
      },
      {
        _key: 'speaker-gifts',
        name: 'Speaker gifts',
        category: 'speakers',
        amount: 10000,
        optional: false,
      },
      {
        _key: 'org-tshirts',
        name: 'Organizer t-shirts',
        category: 'admin',
        amount: 10000,
        optional: false,
      },
      {
        _key: 'accounting',
        name: 'Accounting',
        category: 'admin',
        amount: 5000,
        optional: false,
      },
      {
        _key: 'meetup',
        name: 'Meetup.com',
        category: 'admin',
        amount: 2000,
        optional: false,
      },
      {
        _key: 'hosting',
        name: 'Web hosting',
        category: 'admin',
        amount: 5000,
        optional: false,
      },
      {
        _key: 'buffer',
        name: 'Miscellaneous / buffer',
        category: 'other',
        amount: 5000,
        optional: false,
      },
    ],
    scenarios: [
      scenario(
        'conservative',
        'Conservative',
        'Cautious sales, optional costs cut',
        {
          'conf-early-bird': 20,
          'conf-standard': 60,
          'conf-late-bird': 10,
          'ws-early-bird': 10,
          'ws-standard': 30,
          'ws-late-bird': 5,
          student: 5,
          'sponsor-discount': 50,
          'sponsor-ws-upgrade': 10,
          speaker: 40,
          organizer: 10,
          volunteer: 10,
        },
        { 'community-partner': 10 },
        { 'speakers-dinner': 1, afterparty: 1 },
        ['streaming-av', 'photography', 'barista-bar'],
      ),
      scenario(
        'baseline',
        'Baseline',
        'Similar to last edition, full costs',
        {
          'conf-early-bird': 25,
          'conf-standard': 75,
          'conf-late-bird': 15,
          'ws-early-bird': 15,
          'ws-standard': 40,
          'ws-late-bird': 10,
          student: 5,
          'sponsor-discount': 60,
          'sponsor-ws-upgrade': 15,
          speaker: 45,
          organizer: 10,
          volunteer: 15,
        },
        { 'community-partner': 15 },
        { 'speakers-dinner': 1, track: 1, afterparty: 1 },
      ),
      scenario(
        'target',
        'Target',
        'Growth target',
        {
          'conf-early-bird': 30,
          'conf-standard': 90,
          'conf-late-bird': 20,
          'ws-early-bird': 20,
          'ws-standard': 50,
          'ws-late-bird': 10,
          student: 10,
          'sponsor-discount': 80,
          'sponsor-ws-upgrade': 20,
          speaker: 50,
          organizer: 10,
          volunteer: 15,
        },
        { 'community-partner': 20 },
        {
          streaming: 1,
          'speakers-dinner': 1,
          lanyard: 1,
          track: 2,
          afterparty: 1,
        },
      ),
      scenario(
        'optimistic',
        'Optimistic',
        'Stretch goal, all add-ons sold',
        {
          'conf-early-bird': 40,
          'conf-standard': 110,
          'conf-late-bird': 25,
          'ws-early-bird': 25,
          'ws-standard': 60,
          'ws-late-bird': 15,
          student: 10,
          'sponsor-discount': 100,
          'sponsor-ws-upgrade': 25,
          speaker: 55,
          organizer: 10,
          volunteer: 15,
        },
        { 'community-partner': 25 },
        {
          streaming: 1,
          'speakers-dinner': 1,
          lanyard: 1,
          barista: 1,
          track: 3,
          afterparty: 2,
        },
      ),
    ],
  }
}
