import { describe, expect, it } from 'vitest'

import { defaultBudgetSeed } from './defaults'
import { budgetDocumentToModel } from './mapper'
import { computeScenario } from './model'
import type { ConferenceBudgetDocument } from './types'

function seedDocument(): ConferenceBudgetDocument {
  return {
    ...defaultBudgetSeed(),
    _id: 'budget-1',
    conference: { _ref: 'conf-1' },
  }
}

describe('budgetDocumentToModel', () => {
  it('maps keyed arrays and scenario cross-references', () => {
    const model = budgetDocumentToModel(seedDocument())
    expect(model.vatRate).toBe(0.25)
    expect(model.ticketingFeeRate).toBe(0.045)
    expect(model.ticketTypes).toHaveLength(13)
    expect(model.scenarios.map((s) => s.name)).toEqual([
      'Conservative',
      'Baseline',
      'Target',
      'Optimistic',
    ])
    const baseline = model.scenarios[1]
    expect(baseline.ticketCounts['conf-standard']).toBe(75)
    expect(baseline.tierCounts['community-partner']).toBe(15)
    expect(baseline.addonCounts['speakers-dinner']).toBe(1)
    const sponsorIncluded = model.ticketTypes.find((t) => t.sponsorIncluded)
    expect(sponsorIncluded?.key).toBe('sponsor-included')
  })

  it('defaults dinner participation when absent', () => {
    const doc = seedDocument()
    delete doc.dinnerParticipation
    const model = budgetDocumentToModel(doc)
    expect(model.dinnerParticipation).toEqual({
      floor: 0.4,
      base: 0.9,
      decay: 1000,
    })
  })

  /**
   * End-to-end invariant: the seeded template computed through the mapper
   * reproduces the reference implementation's Baseline for the same
   * (synthetic) inputs — the seed's figures are generic placeholders, and
   * these expectations were regenerated by running CloudNativeBergen/budget
   * against them (see the fixture note in model.test.ts for the how-to).
   */
  it('seed template Baseline matches the reference implementation', () => {
    const model = budgetDocumentToModel(seedDocument())
    const baseline = model.scenarios.find((s) => s.name === 'Baseline')!
    const r = computeScenario(model, baseline)
    expect(r.headcounts.conference).toBe(345)
    expect(r.headcounts.workshop).toBe(80)
    expect(r.headcounts.crew).toBe(70)
    expect(r.headcounts.totalTickets).toBe(360)
    expect(r.ticketRevenue).toBeCloseTo(719848.0, 5)
    expect(r.sponsorRevenue).toBeCloseTo(445000.0, 5)
    expect(r.totalIncome).toBeCloseTo(1164848.0, 5)
    expect(r.totalVariableExpenses).toBeCloseTo(527041.45, 3)
    expect(r.totalFixedExpenses).toBeCloseTo(562000, 5)
    expect(r.netResult).toBeCloseTo(75806.55, 3)
  })

  it('cuts optional costs in the Conservative scenario', () => {
    const model = budgetDocumentToModel(seedDocument())
    const conservative = model.scenarios.find((s) => s.name === 'Conservative')!
    const r = computeScenario(model, conservative)
    expect(r.totalFixedExpenses).toBeCloseTo(397000, 5)
    expect(
      r.expenseLines.find((line) => line.key === 'streaming-av')?.cut,
    ).toBe(true)
  })
})
